version: "3.6"
services:
  # The Application
  php:
    build:
      context: ./
      dockerfile: dockerfile-php
    working_dir: /src
    volumes:
      - ./html477/grav:/src
      # show php info..
      # - ./src:/src
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    ports:
      - "9001:9000"

  # The Web Server
  nginx:
    image: nginx:1.16-alpine
    # build:
    #   context: ./
    #   dockerfile: web.dockerfile
    working_dir: /src
    links:
      - php
    ports:
      - 8085:80
    volumes:
      - ./docker-nginx-vhost.conf:/etc/nginx/conf.d/default.conf
  # The Database
  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   environment:
  #     - "MYSQL_DATABASE=homestead"
  #     - "MYSQL_USER=homestead"
  #     - "MYSQL_PASSWORD=secret"
  #     - "MYSQL_ROOT_PASSWORD=secret"
  #   ports:
  #     - "33061:3306"
# volumes:
#   dbdata:
