version: '3.6'
services:
  nginx:
    image: nginx:1.14-alpine
    ports:
     - 8091:80
    restart: always
    volumes:
     - ./docker/nginx/nginxmain.conf:/etc/nginx/nginx.conf
     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./index.html:/usr/share/nginx/html/index.html
        