# proxyseafile - https://github.com/dgleba/422dkrcol/tree/master/proxyseafile

version: "3.6"

# custom config for jwilder..
# https://stackoverflow.com/questions/39514293/docker-nginx-proxy-how-to-route-traffic-to-different-container-using-path-and-n?rq=1

services:
  nginxproxy:
    image: jwilder/nginx-proxy:alpine
    #user: "${UID}:${GID}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./jw-vhost.d/:/etc/nginx/vhost.d
      - ./certs/:/etc/nginx/certs:ro
      - ./jw-html/:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    # networks:
    #   - sister

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9
    depends_on:
      - nginxproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./jw-vhost.d/:/etc/nginx/vhost.d
      - ./certs/:/etc/nginx/certs:rw
      - ./jw-html/:/usr/share/nginx/html
    restart: always
    # links will share the volumes between containers.
    links:
      - nginxproxy

  seafile:
    image: seafileltd/seafile:6.2.5
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../datasys/seafiledata:/shared
    ports:
      - "6311:80"
    expose:
      - "80"
      - "8000"
      - "8082"
    environment:
      - VIRTUAL_HOST=sf-104-193-61-58.nip.io
      - LETSENCRYPT_HOST=sf-104-193-61-58.nip.io
      - LETSENCRYPT_EMAIL=d@gmail.com
