version: "3.6"

x-redash-service: &redash-service
  image: redash/redash:7.0.0.b18042
  depends_on:
    - postgres
    - redis
  env_file: .env
  restart: always
  networks:
    - sister

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      - REDASH_WEB_WORKERS=4
    networks:
      - sister

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
    networks:
      - sister

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
    networks:
      - sister

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
    networks:
      - sister

  redis:
    image: redis:5.0-alpine
    restart: always
    networks:
      - sister

  postgres:
    image: postgres:9.5-alpine
    env_file: .env
    volumes:
      - ../datasys/redash-postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - sister

  nginx:
    image: redash/nginx:latest
    # ports:
    #   - "80:80"
    expose:
      - 80
    depends_on:
      - server
    links:
      - server:redash
    restart: always
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=rd-104-193-61-58.nip.io
      - LETSENCRYPT_HOST=rd-104-193-61-58.nip.io
      - LETSENCRYPT_EMAIL=d@gmail.com
    networks:
      - sister

networks:
  sister:
    name: sister
      external:true
