version: "3.6"
services:
  apache:
    # https://gist.github.com/Mikulas/449746102591d636640467910eaf8aad
    build: ./
    # labels:
      # - "traefik.backend=alpine"
      # - "traefik.frontend.rule=Host:alpine.docker.localhost"
    environment:
      - MYSQL_HOST=mysql
      - APACHE_SERVER_NAME=alpine424b.docker.localhost
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_HTML_ERRORS=On
      - PHP_XDEBUG_ENABLED=true
    # networks:
      # - default
    volumes:
      - ./public:/app
    cap_add:
      - SYS_TIME
      - SYS_NICE
# networks:
  # default:
    # external:
      # name: docker_docker-localhost
