version: "3.6"

services:
  pydio:
    image: brunneis/pydio-centos
    # container_name: pydio-core
    volumes:
      - pydfile:/var/www/html/data/files
      - pydpers:/var/www/html/data/personal
    ports:
      - 8081:80
    environment:
      - VIRTUAL_HOST=pyd8-108-168-7-171.nip.io
      - LETSENCRYPT_HOST=pyd8-108-168-7-171.nip.io
      - LETSENCRYPT_EMAIL=d@gmail.com
    networks:
      - sister
    expose:
      - "80"

  mariadb:
    image: mariadb
    # container_name: pydio-database
    volumes:
      - maria475:/var/lib/mysql/ # folder for mysql's internal data files.
      # - .:/root # folder for scripts, etc.
      # - ../data/maria475/:/home # folder for exported data, etc.
    env_file:
      - .env
    networks:
      - sister
    ports:
      - "3307:3306"

  #
  # web:
  #   # to test this jwilder/LE
  #   # http://web456-108-168-7-24.nip.io/
  #   # https://web456-108-168-7-24.nip.io/
  #   image: nginx:1.15-alpine
  #   # container_name: example-webapp
  #   volumes:
  #     - ./nindex.html:/usr/share/nginx/html/index.html
  #   expose:
  #     - "80"
  #   environment:
  #     - VIRTUAL_HOST=web456-108-168-7-24.nip.io
  #     - VIRTUAL_PORT=80
  #     - LETSENCRYPT_HOST=web456-108-168-7-24.nip.io
  #     - LETSENCRYPT_EMAIL=dgleba@gmail.com
  #   restart: always
  #   networks:
  #     - sister

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vol/nginx/vhost.d:/etc/nginx/vhost.d
      - ./vol/nginx/certs:/etc/nginx/certs:ro
      - ./vol/nginx/html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    networks:
      - sister
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "49"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vol/nginx/vhost.d:/etc/nginx/vhost.d
      - ./vol/nginx/certs:/etc/nginx/certs:rw
      - ./vol/nginx/html:/usr/share/nginx/html
    restart: always
    networks:
      - sister
    # links will share the volumes between containers.
    links:
      - nginx-proxy

networks:
  sister:
    name: sister

volumes:
  maria475:
  pydfile:
  pydpers:
