version: "3.6"

services:
  php:
    image: php:7.2-apache
    volumes:
      #  # container folder to sync. You set it..
      - quick-sync-volume:/etc/apache2/conf-enabled
    # volumes:
    #   - type: volume
    #     source: quick-sync-volume
    #     target: /etc/apache2/conf-enabled

  php_sync:
    # image: codycraven/quick-bind-sync:latest
    build:
      context: ./
      dockerfile: Dockerfile-qbsync
    depends_on:
      - php
    volumes:
      - quick-sync-volume:/volume # reserved name for this sync tool
      - type: bind
        # host folder to sync. You set it..
        source: ../x/a2conf
        target: /host # reserved name for this sync tool
      # - type: volume
      #   source: quick-sync-volume
      #   target: /volume

volumes:
  quick-sync-volume:
