version: '3.6'

 #        http://192.168.88.60:6301/ponotepad

services:
    web:
        image: nginx:1.15-alpine
        ports:
            - "6301:6302"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:7.3.3-fpm-alpine
        volumes:
            - ./code:/code
        networks:
            - code-network


networks:
    code-network:
        driver: bridge

     