version: "3.6"

# custom config for jwilder..
# https://stackoverflow.com/questions/39514293/docker-nginx-proxy-how-to-route-traffic-to-different-container-using-path-and-n?rq=1

services:
  nginxproxy459le:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vol/vhost.d/:/etc/nginx/vhost.d
      - ./vol/certs/:/etc/nginx/certs:ro
      - ./vol/html/:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    # networks:
    #   - sister

  gateway:
    image: nginx:1.15-alpine
    volumes:
      - ./nindex.html:/usr/share/nginx/html/index.html
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=gw-104-193-61-58.nip.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=gw-104-193-61-58.nip.io
      - LETSENCRYPT_EMAIL=d@gmail.com
    restart: always

  app1:
    image: jwilder/whoami

  app2:
    image: jwilder/whoami

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9
    depends_on:
      - nginxproxy459le
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vol/vhost.d/:/etc/nginx/vhost.d
      - ./vol/certs/:/etc/nginx/certs:rw
      - ./vol/html/:/usr/share/nginx/html
    restart: always
    # links will share the volumes between containers.
    links:
      - nginxproxy459le
