###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: dkr417bphp-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: dkr417bphp-mailhog
      ports:
        - "3103:8025"

    redis:
      image: redis:alpine
      container_name: dkr417bphp-redis

    mysql:
      image: mysql:8.0
      container_name: dkr417bphp-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db1
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
      ports:
        - "3104:3306"

    mariadb:
      image: mariadb:10.1
      container_name: dkr417bphp-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
      ports:
        - "3105:3306"

    postgres:
      image: postgres:9.6-alpine
      container_name: dkr417bphp-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=app

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: dkr417bphp-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: dkr417bphp-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3102:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: dkr417bphp-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

